---

### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "AgileHome"
keywords:    "AgileHome, universidad, granada, ugr, etsiit, informatica, mda, metodologias, desarrollo, agil"
description: "AgileHome es un proyecto para Metodologías de Desarrollo Ágiles, del grado de Ingeniería Informática, UGR"
source_link: "https://agilehome.github.io"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: 

### template colors, used site-wide via css ###
colors:
  darkgray:   '#2e2e2e'
  grisecillo: '#444444'
  black:      '#111111'
  white:      '#f8f8f8'
  blue:       '#49a7e9'
  green:      '#9bcf2f'
  purple:     '#c869bf'
  orange:     '#fab125'
  turquoise:  '#0fbfcf'

kramdown:
  auto_ids:  false
